version: '3.6'

networks:
  app:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.17
    restart: on-failure
    container_name: api_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_api_mysql
  
  api:
   build:
    context: api
   container_name: api_app
   networks:
     - app
   ports:
     - '3030:3030'
   volumes:
     - "/var/www/node_modules"
     - "./api:/var/www"
   command: "npm run dev"    

